### ISSUE TITLE
Bug Report - (batched option & tensor shape)

### ISSUE THREAD

**Issue by sunyuhan19981208** [sail-sg/lorahub#9]
# Description
I have met some bugs while running `python example.py`
## 1. batched problem
If setting `batched=True` at `algorithm.py: 105` by default in your code, the exception below raised:
``` python
Traceback (most recent call last):
  File "/data/sdb/sunyuhan/exp/lorahub/example.py", line 239, in <module>
    main()
  File "/data/sdb/sunyuhan/exp/lorahub/example.py", line 211, in main
    module_weights, model, tokenizer = lorahub_learning(lora_module_list=modules,
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 264, in lorahub_learning
    dataset = load_dataset(example_inputs, example_outputs, tokenizer) 
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 103, in load_dataset
    processed_datasets = dataset.map(
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2092, in map
    return self._map_single(
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/fingerprint.py", line 411, in wrapper
    out = func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2469, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2361, in apply_function_on_filtered_inputs
    validate_function_output(processed_inputs, indices)
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2340, in validate_function_output
    raise TypeError(
TypeError: Provided `function` which is applied to all elements of table returns a `dict` of types [<class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>]. When using `batched=True`, make sure provided `function` returns a `dict` of types like `(<class 'list'>, <class 'numpy.ndarray'>)`.
```
**Solution** : set `batched=False`:
``` python
processed_datasets = dataset.map(
    preprocess_func_with_tokenizer,
  ->batched=False,
    num_proc=1,
    desc="Running tokenizer on dataset",
)
```
## 2. padding problem
All the padding value is `True` currently, and the exception below raised:
``` python
Traceback (most recent call last):
  File "/data/sdb/sunyuhan/exp/lorahub/example.py", line 239, in <module>
    main()
  File "/data/sdb/sunyuhan/exp/lorahub/example.py", line 211, in main
    module_weights, model, tokenizer = lorahub_learning(lora_module_list=modules,
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 279, in lorahub_learning
    recommendation = optimizer.minimize(get_score_partial, verbosity=1)
  File "/root/miniconda3/lib/python3.10/site-packages/nevergrad/optimization/base.py", line 671, in minimize
    result = job.result()
  File "/root/miniconda3/lib/python3.10/site-packages/nevergrad/optimization/utils.py", line 137, in result
    self._result = self.func(*self.args, **self.kwargs)
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 165, in get_score
    loss = get_loss(example_dataset, model, batch_size)
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 127, in default_get_loss
    for _, batch in enumerate(train_dataloader):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/data/data_collator.py", line 70, in default_data_collator
    return torch_default_data_collator(features)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/data/data_collator.py", line 136, in torch_default_data_collator
    batch[k] = torch.tensor([f[k] for f in features])
ValueError: expected sequence of length 81 at dim 2 (got 90)
```
**Solution** : set all paddings in `algorithm.py` to `'max_length'`:
``` python
inputs = tokenizer(
    dataset["input"][i : i + batch_size],
    max_length=2048,
    return_tensors="pt",
  ->padding='max_length',
).to(device)
```
## 3. tensor dimension problem
The shape of input has now became `[5, 1, 2048]` due to the modifies before:
``` python
(Pdb) p batch['input_ids'].shape
torch.Size([5, 1, 2048])
```
And it will cause shape error:
``` python
Traceback (most recent call last):
  File "/data/sdb/sunyuhan/exp/lorahub/example.py", line 239, in <module>
    main()
  File "/data/sdb/sunyuhan/exp/lorahub/example.py", line 211, in main
    module_weights, model, tokenizer = lorahub_learning(lora_module_list=modules,
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 280, in lorahub_learning
    recommendation = optimizer.minimize(get_score_partial, verbosity=1)
  File "/root/miniconda3/lib/python3.10/site-packages/nevergrad/optimization/base.py", line 671, in minimize
    result = job.result()
  File "/root/miniconda3/lib/python3.10/site-packages/nevergrad/optimization/utils.py", line 137, in result
    self._result = self.func(*self.args, **self.kwargs)
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 166, in get_score
    loss = get_loss(example_dataset, model, batch_size)
  File "/data/sdb/sunyuhan/exp/lorahub/lorahub/algorithm.py", line 131, in default_get_loss
    outputs = model(**batch)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 1080, in forward
    return self.base_model(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1678, in forward
    encoder_outputs = self.encoder(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 986, in forward
    batch_size, seq_length = input_shape
ValueError: too many values to unpack (expected 2)
```
**Solution** : squeeze the unused dimension at `algorithm.py:128`:
``` python
with torch.no_grad():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    for _, batch in enumerate(train_dataloader):
      ->batch = {k: v.squeeze(1).to(device) for k, v in batch.items()}
        with torch.no_grad():
            outputs = model(**batch)
        loss = outputs.loss
        train_loss += loss.detach().float()
```
## Summarization
All the bugs maybe caused by setting `batched=False`, but I can not set the `batched=True` due to unknown reason. And after above 3 modifies I can successfully run the `example.py`.

**Comment by SivilTaram** [comment]
@sunyuhan19981208 Since our codebase is hosted on several demo spaces and it works well, I do not think there should be some bugs on the codebase itself. Can you check your environment at first? Maybe the `datasets` lib does not support the batched option?

**Comment by sunyuhan19981208** [comment]
@SivilTaram This is my datasets lib:
```
#pip show datasets
Name: datasets
Version: 1.17.0
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: /root/miniconda3/lib/python3.10/site-packages
Requires: aiohttp, dill, fsspec, huggingface-hub, multiprocess, numpy, packaging, pandas, pyarrow, requests, tqdm, xxhash
Required-by: FlagEmbedding, lorahub
```

**Comment by SivilTaram** [comment]
@sunyuhan19981208 Below are the environments we can run the code:
```
Name: datasets
Version: 2.13.1
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: /mnt/home/liuqian/miniconda/envs/lorahub/lib/python3.9/site-packages
Requires: aiohttp, dill, fsspec, huggingface-hub, multiprocess, numpy, packaging, pandas, pyarrow, pyyaml, requests, tqdm, xxhash
Required-by: evaluate
```

**Comment by sunyuhan19981208** [comment]
@SivilTaram Thank you!!!!! `pip install datasets==2.13.1` works for me.
